sudo: required
services:
  - docker

before_install:
  - docker build -t marcelkawski/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true marcelkawski/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'eu-north-1' # from the app URL
  app: 'docker-react'
  env: 'Dockerreact-env'
  bucket_name: 'elasticbeanstalk-eu-north-1-343270885324'
  bucket_path: 'docker-react'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: '$AWS_SECRET_KEY'
