sudo: required
services:
  - docker

before_install:
  - docker build -t marcelkawski/docker-react2 -f Dockerfile.dev .

script:
  - docker run -e CI=true marcelkawski/docker-react2 npm run test
