version: "3"
services:
  web: # React app
    # build: . # It assumes we have a Dockerfile inside our working directory.
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app # <curr work dir>:<dir inside the container>
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"] # to override default starting command: npm run start
