FROM node:16-alpine
WORKDIR '/app'
COPY package.json .
RUN npm install
# solution of one problem from Stackoverflow
RUN mkdir -p node_modules/.cache && chmod -R 777 node_modules/.cache
COPY . .
CMD ["npm", "run", "start"]